apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: a9ec6jk66-dotnet-basic
  janus-idp.io/tekton: a9ec6jk66-dotnet-basic
  backstage.io/kubernetes-id: a9ec6jk66-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: a9ec6jk66-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
